export const ADDMANAGER_REQUEST = "ADDMANAGER_REQUEST";
export const ADDMANAGER_SUCCESS = "ADDMANAGER_SUCCESS";
export const ADDMANAGER_FAIL = "ADDMANAGER_FAIL";
export const ADDMANAGER_RESET = "ADDMANAGER_RESET";
